name: thesis_track_app
description: "A Flutter application for thesis tracking system."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  phosphor_flutter: ^2.0.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        # - asset: assets/fonts/Poppins-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/Poppins-SemiBold.ttf
        #   weight: 600
        # - asset: assets/fonts/Poppins-Bold.ttf
        #   weight: 700
